artifact_uri: file:///usr/users/demo_arthur/nobile_tob/patchcore-inspection/mlruns_array/702298048823873848/725cc65731234ae589282ff19af6333f/artifacts
end_time: 1783516041190
entry_point_name: ''
experiment_id: '702298048823873848'
lifecycle_stage: active
run_id: 725cc65731234ae589282ff19af6333f
run_name: inspect_heatmap_approx_greedy_coreset_p0.01
source_name: ''
source_type: 4
source_version: ''
start_time: 1783516040473
status: 3
tags: []
user_id: nobile_tob
