artifact_uri: file:///usr/users/demo_arthur/nobile_tob/patchcore-inspection/mlruns_array/702298048823873848/d92de982b6e647f1a566758ef01b4077/artifacts
end_time: 1783516170206
entry_point_name: ''
experiment_id: '702298048823873848'
lifecycle_stage: active
run_id: d92de982b6e647f1a566758ef01b4077
run_name: inspect_heatmap_approx_greedy_coreset_p0.1
source_name: ''
source_type: 4
source_version: ''
start_time: 1783516169083
status: 3
tags: []
user_id: nobile_tob
