artifact_location: file:///usr/users/demo_arthur/nobile_tob/patchcore-inspection/mlruns_array/702298048823873848
creation_time: 1783515920871
effective_trace_archival_retention: null
experiment_id: '702298048823873848'
last_update_time: 1783515920871
lifecycle_stage: active
name: CelebA_Results
trace_location: null
workspace: default
