artifact_uri: file:///usr/users/demo_arthur/nobile_tob/patchcore-inspection/mlruns_array/702298048823873848/5d7ba93159b74ba9b7ab3616516dab7a/artifacts
end_time: 1783516009753
entry_point_name: ''
experiment_id: '702298048823873848'
lifecycle_stage: active
run_id: 5d7ba93159b74ba9b7ab3616516dab7a
run_name: inspect_heatmap_identity_nopct
source_name: ''
source_type: 4
source_version: ''
start_time: 1783516005037
status: 3
tags: []
user_id: nobile_tob
