artifact_uri: file:///usr/users/demo_arthur/nobile_tob/patchcore-inspection/mlruns_array/702298048823873848/f9c6eba1d42a47538b963b92112b6eb4/artifacts
end_time: 1783516005005
entry_point_name: ''
experiment_id: '702298048823873848'
lifecycle_stage: active
run_id: f9c6eba1d42a47538b963b92112b6eb4
run_name: inspect_heatmap_identity_nopct
source_name: ''
source_type: 4
source_version: ''
start_time: 1783516000119
status: 3
tags: []
user_id: nobile_tob
